# Generated by Django 5.0.2 on 2024-02-27 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sort_description', models.TextField(blank=True, null=True)),
                ('full_detail', models.TextField(blank=True, null=True)),
                ('product_tag', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sort_description', models.TextField(blank=True, null=True)),
                ('full_detail', models.TextField(blank=True, null=True)),
                ('product_tag', models.CharField(max_length=200, null=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('availability', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=100)),
                ('product_type', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('size', models.JSONField(blank=True, default=list, null=True)),
                ('description', models.TextField()),
                ('product_tag', models.CharField(max_length=200, null=True)),
                ('product_image', models.ImageField(null=True, upload_to='product')),
                ('product_image1', models.ImageField(null=True, upload_to='product')),
                ('product_image2', models.ImageField(null=True, upload_to='product')),
                ('product_image3', models.ImageField(null=True, upload_to='product')),
                ('product_image4', models.ImageField(null=True, upload_to='product')),
                ('product_image5', models.ImageField(null=True, upload_to='product')),
                ('product_image6', models.ImageField(null=True, upload_to='product')),
                ('quantity', models.IntegerField(null=True)),
                ('full_detail', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color1', models.CharField(default='#ff6191', max_length=7)),
                ('color2', models.CharField(default='#33317d', max_length=7)),
                ('color3', models.CharField(default='#56d4b7', max_length=7)),
                ('color4', models.CharField(default='#009688', max_length=7)),
                ('colors', models.JSONField(blank=True, default=list, null=True)),
                ('custom_size', models.TextField(blank=True, null=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.subcategory')),
            ],
        ),
    ]
