# Generated by Django 5.0.2 on 2024-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_backgroundsliders_childsliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsliders',
            name='heading1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backgroundsliders',
            name='heading2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
