# Generated by Django 5.0.2 on 2024-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_backgroundsliders_heading1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsliders',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
