# Generated by Django 5.0.2 on 2024-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_backgroundsliders_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_choice',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
