# Generated by Django 5.0.2 on 2024-07-08 14:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_useradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('faq', 'FAQ'), ('about', 'About'), ('contact', 'Contact')], max_length=20, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
