# Generated by Django 5.0.2 on 2024-03-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_customer_orderplaced_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='user',
        ),
    ]
