# Generated by Django 5.0.2 on 2024-03-27 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_product_admin_choice'),
        ('userapp', '0007_imageupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_imageupload', to='adminapp.product'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_imageuplaod', to=settings.AUTH_USER_MODEL),
        ),
    ]
