# Generated by Django 5.0.2 on 2024-04-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_orderplaced_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
