# Generated by Django 5.0.2 on 2024-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_orderplaced_amount_alter_orderplaced_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
