# Generated by Django 5.0.2 on 2024-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_orderplaced_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
