# Generated by Django 5.0.2 on 2024-04-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_subcategory_image'),
        ('userapp', '0016_alter_orderplaced_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.product'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, null=True, unique=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(null=True)),
                ('status', models.CharField(default='Order Placed', max_length=50)),
                ('payment_method', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.customer')),
                ('payment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.order'),
        ),
    ]
