# Generated by Django 5.0.2 on 2024-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_remove_orderplaced_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_expected_date',
            field=models.DateField(null=True),
        ),
    ]
