# Generated by Django 5.0.2 on 2024-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_order_delivery_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='customer-images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='customer-images/'),
        ),
    ]
