# Generated by Django 5.0.2 on 2024-04-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_customer_email_customer_image1_customer_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address3',
            field=models.TextField(null=True),
        ),
    ]
