# Generated by Django 5.0.2 on 2024-04-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_rename_email_customer_email1_customer_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
