# Generated by Django 5.0.2 on 2024-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_alter_customer_city_alter_customer_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.TextField(null=True),
        ),
    ]
