# Generated by Django 5.0.2 on 2024-06-03 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_order_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='address_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.customer'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='delivery_expected_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='order_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='status',
            field=models.CharField(default='Order Placed', max_length=50),
        ),
    ]
