# Generated by Django 5.0.2 on 2024-06-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_imageupload_address_id_imageupload_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='payment_method',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
