# Generated by Django 5.0.2 on 2024-06-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_imageupload_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
